"""Application-wide constants."""

APP_NAME = "Novaris AI Backend"
APP_VERSION = "0.1.0"
API_V1_PREFIX = "/api/v1"

DECISION_ALLOW = "ALLOW"
DECISION_MONITOR = "MONITOR"
DECISION_REVIEW = "REVIEW"
DECISION_TEMPORARY_BLOCK = "TEMPORARY_BLOCK"

RISK_LEVEL_LOW = "Faible"
RISK_LEVEL_MODERATE = "Modéré"
RISK_LEVEL_HIGH = "Élevé"
RISK_LEVEL_CRITICAL = "Critique"

